name: build cfg_merge

on:
  push:
    branches:
      - master
  release:
    types:
      - published
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # This is needed for creating releases

jobs:
  build:
    name: cross-compile builds
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - name: windows-x86_64
            zig_target: x86_64-windows
            extension: .exe

          - name: macos-x86_64
            zig_target: x86_64-macos
            extension: ""

          - name: macos-aarch64
            zig_target: aarch64-macos
            extension: ""

          - name: linux-x86_64
            zig_target: x86_64-linux
            extension: ""

          - name: linux-aarch64
            zig_target: aarch64-linux
            extension: ""

          - name: linux-arm
            zig_target: arm-linux-gnueabi
            extension: ""

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      - name: build for ${{ matrix.target.name }}
        run: |
          zig build-exe main.zig -target ${{ matrix.target.zig_target }} -O ReleaseSmall -fstrip -fsingle-threaded --name cfg_merge
          mkdir -p dist
          cp cfg_merge${{ matrix.target.extension }} dist/cfg_merge-${{ matrix.target.name }}${{ matrix.target.extension }}

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cfg_merge-${{ matrix.target.name }}
          path: dist/cfg_merge-${{ matrix.target.name }}${{ matrix.target.extension }}

  release:
    name: create release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || github.event.action == 'published'

    steps:
      - name: download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts

      - name: create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/**/*
          draft: false
          prerelease: false